import { Ledger } from "./managed/murmur/contract/index.js";
import { WitnessContext } from "@midnight-ntwrk/midnight-js-protocol/compact-runtime";

export type MurmurPrivateState = {
  readonly respondentSecret: Uint8Array;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  readonly respondentPath: any; // MerkleTreePath shape generated by Compact
};

export const createMurmurPrivateState = (
  respondentSecret: Uint8Array,
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  respondentPath: any
): MurmurPrivateState => ({
  respondentSecret,
  respondentPath,
});

export const witnesses = {
  respondentSecret: ({
    privateState,
  }: WitnessContext<Ledger, MurmurPrivateState>): [
    MurmurPrivateState,
    Uint8Array,
  ] => [privateState, privateState.respondentSecret],

  respondentPath: ({
    privateState,
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  }: WitnessContext<Ledger, MurmurPrivateState>): [MurmurPrivateState, any] =>
    [privateState, privateState.respondentPath],
};
